### ISSUE TITLE
Экранирование кавычек

### ISSUE THREAD

**Issue by Bwca** [k0r0tk0ff/kafka-spring-boot-mvc-sample#1]
https://github.com/k0r0tk0ff/kafka-spring-boot-mvc-sample/blob/01c93b86c4837c401b3ee208a36b1531454ab3e8/src/main/resources/static/js/misc.js#L1

Экранирования можно избежать если строка заключена в одинарные кавычки вместо двойных. Вообще выбери один стиль и придерживайся его, а еще лучше настрой автоформаттер/линтер чтобы исправлял.

**Comment by k0r0tk0ff** [comment]
fixed
