### ISSUE TITLE
К DOM лучше обращаться здесь

### ISSUE THREAD

**Issue by Bwca** [k0r0tk0ff/kafka-spring-boot-mvc-sample#11]
https://github.com/k0r0tk0ff/kafka-spring-boot-mvc-sample/blob/90d41f5cf18a685be1dd0a08072fcffd20d58999/src/main/resources/static/js/misc.js#L21

Как раз внутри этого коллбека безопаснее всего обращаться к DOM-элементам по id, селекторам и прочим, т.к. здесь уже гарантировано что они загружены.

**Comment by k0r0tk0ff** [comment]
fixed
