### ISSUE TITLE
Здесь можно использовать объект

### ISSUE THREAD

**Issue by Bwca** [k0r0tk0ff/kafka-spring-boot-mvc-sample#2]
https://github.com/k0r0tk0ff/kafka-spring-boot-mvc-sample/blob/01c93b86c4837c401b3ee208a36b1531454ab3e8/src/main/resources/static/js/misc.js#L3

1. Идеологически это не может быть let потому что это константа.
2. Громоздко, тебе по сути нужен объект с неизменяемыми полями, это можно сделать при помощи [freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze).

**Comment by k0r0tk0ff** [comment]
fixed
