### ISSUE TITLE
Можно записать короче

### ISSUE THREAD

**Issue by Bwca** [k0r0tk0ff/kafka-spring-boot-mvc-sample#5]
https://github.com/k0r0tk0ff/kafka-spring-boot-mvc-sample/blob/01c93b86c4837c401b3ee208a36b1531454ab3e8/src/main/resources/static/js/misc.js#L29

Эквивалентно  _.then(console.log)_

**Comment by k0r0tk0ff** [comment]
Я оставлю так как есть, ибо пока так, ибо так понятно что тут работает lambda
