### ISSUE TITLE
Вызовы функций можно сократить

### ISSUE THREAD

**Issue by Bwca** [k0r0tk0ff/kafka-spring-boot-mvc-sample#7]
https://github.com/k0r0tk0ff/kafka-spring-boot-mvc-sample/blob/01c93b86c4837c401b3ee208a36b1531454ab3e8/src/main/resources/static/js/misc.js#L56-L57

Аналогично с issue с консолем.

**Comment by k0r0tk0ff** [comment]
Я пока воздержусь от сокращенной формы, ибо читаемость кода ИМХО снижается
