### ISSUE TITLE
Лучше обернуть

### ISSUE THREAD

**Issue by Bwca** [k0r0tk0ff/kafka-spring-boot-mvc-sample#9]
https://github.com/k0r0tk0ff/kafka-spring-boot-mvc-sample/blob/01c93b86c4837c401b3ee208a36b1531454ab3e8/src/main/resources/static/js/misc.js#L33

Прежде чем навешивать слушатели на элементы, нужно [дождаться прогрузки DOM-дерева](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event).

**Comment by k0r0tk0ff** [comment]
fixed
